:concurrency: 5
:queues:
- default
- metrics
- mailers
- newsletter
- events
- scheduled

:schedule:
  CalculateAllMetrics:
    cron: '0 0 0 * * *'
    class: CalculateAllMetricsJob
    queue: scheduled
  PreloadOpenData:
    cron: '0 0 0 * * *'
    class: PreloadOpenDataJob
    queue: scheduled
  OrdersReminder:
    cron: '0 0 0 * * *'
    class: OrdersReminderJob
    queue: scheduled
  DestroyInactiveUsers:
    cron: '0 0 0 * * *'
    class: DestroyInactiveUsersJob
    queue: scheduled
